# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-30 08:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id_car', models.AutoField(primary_key=True, serialize=False)),
                ('number', models.CharField(max_length=10, unique=True)),
                ('pts', models.CharField(blank=True, max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id_customer', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id_driver', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Mediator',
            fields=[
                ('id_mediator', models.AutoField(primary_key=True, serialize=False)),
                ('address', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Milage',
            fields=[
                ('id_milage', models.AutoField(primary_key=True, serialize=False)),
                ('start_milage', models.IntegerField()),
                ('end_milage', models.IntegerField()),
                ('id_driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Avtoregion.Driver')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id_product', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Race',
            fields=[
                ('id_race', models.AutoField(primary_key=True, serialize=False)),
                ('name_race', models.CharField(default='Рейс', max_length=5)),
                ('race_date', models.DateField()),
                ('type_ship', models.BooleanField(default=0)),
                ('s_milage', models.FloatField(default=0)),
                ('e_milage', models.FloatField(default=0)),
                ('weight_load', models.FloatField(default=0)),
                ('weight_unload', models.FloatField(default=0)),
                ('comm', models.TextField()),
                ('state', models.IntegerField(default=0)),
                ('create_time', models.DateTimeField(auto_now=True)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Avtoregion.Car')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Avtoregion.Customer')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Avtoregion.Driver')),
                ('mediator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Avtoregion.Mediator')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Avtoregion.Product')),
            ],
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id_shipment', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id_supplier', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Trailer',
            fields=[
                ('id_trailer', models.AutoField(primary_key=True, serialize=False)),
                ('number', models.CharField(max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='race',
            name='shipment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Avtoregion.Shipment'),
        ),
        migrations.AddField(
            model_name='race',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Avtoregion.Supplier'),
        ),
        migrations.AddField(
            model_name='car',
            name='trailer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Avtoregion.Trailer'),
        ),
    ]
