# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-12 12:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Avtoregion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='race',
            name='arrival_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
