# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-14 13:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('Avtoregion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Units',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('short_name', models.CharField(blank=True, max_length=3)),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='units',
        ),
        migrations.AddField(
            model_name='race',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    to='Avtoregion.Units'),
        ),
    ]
