# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-27 10:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Avtoregion', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='id_trailer',
            new_name='trailer',
        ),
        migrations.RenameField(
            model_name='race',
            old_name='id_car',
            new_name='car',
        ),
        migrations.RenameField(
            model_name='race',
            old_name='type',
            new_name='type_ship',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='id_shipment',
        ),
        migrations.RemoveField(
            model_name='race',
            name='milage',
        ),
        migrations.AddField(
            model_name='race',
            name='e_milage',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='race',
            name='s_milage',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='race',
            name='shipment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Avtoregion.Shipment'),
        ),
        migrations.AlterField(
            model_name='race',
            name='weight_load',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='race',
            name='weight_unload',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
