# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-23 11:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Avtoregion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='race',
            name='shoulder',
            field=models.FloatField(default=0),
        ),
    ]
