# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-14 07:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Avtoregion', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='fraction',
        ),
        migrations.AddField(
            model_name='product',
            name='units',
            field=models.CharField(blank=True, max_length=5),
        ),
    ]
