# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-31 07:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Avtoregion', '0002_auto_20180131_1011'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='date_med',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
