# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-12 19:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Avtoregion', '0002_race_arrival_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='race',
            name='race_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
