# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-29 05:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Avtoregion', '0002_auto_20171127_1002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='trailer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Avtoregion.Trailer'),
        ),
        migrations.AlterField(
            model_name='race',
            name='name_race',
            field=models.CharField(default='Рейс', max_length=5),
        ),
        migrations.AlterField(
            model_name='race',
            name='shipment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Avtoregion.Shipment'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
