# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-24 14:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Avtoregion', '0003_auto_20180124_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='constants',
            name='dispatcher',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='constants',
            name='mechanic',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='constants',
            name='organization_unit_full',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='constants',
            name='organization_unit_small',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
