# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-25 09:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Avtoregion', '0004_auto_20180124_1907'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='race',
            name='name_race',
        ),
        migrations.AddField(
            model_name='car',
            name='garage_number',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=10, max_length=5),
        ),
        migrations.AddField(
            model_name='driver',
            name='driver_card',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='driver',
            name='personnel_number',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='race',
            name='gas_end',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='race',
            name='gas_given',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='race',
            name='gas_start',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='trailer',
            name='brand_trailer',
            field=models.CharField(default='85300F', max_length=10),
        ),
        migrations.AddField(
            model_name='trailer',
            name='garage_number_trailer',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=10, max_length=5),
        ),
    ]
