# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-06 17:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Avtoregion', '0014_auto_20171226_1657'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='milage',
            name='id_driver',
        ),
        migrations.AddField(
            model_name='car',
            name='mediator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Avtoregion.Mediator'),
        ),
        migrations.AddField(
            model_name='mediator',
            name='inn',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True, unique=True, verbose_name='ИНН'),
        ),
        migrations.DeleteModel(
            name='Milage',
        ),
    ]
