"""
Django settings for Avtoregion project.

Generated by 'django-admin startproject' using Django 1.11.7.

For more information on this file, see
https://docs.djangoproject.com/en/1.11/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.11/ref/settings/
"""

import os
import hashlib
from envconf import Env


env = Env(DEBUG=(bool, False))
env.read_env()
# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.11/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env('DEBUG')
ALLOWED_HOSTS = env('ALLOWED_HOSTS', cast=list)
INTERNAL_IPS = env('INTERNAL_IPS', cast=list, default=[])
SECURE_CONTENT_TYPE_NOSNIFF = True
SECURE_BROWSER_XSS_FILTER = True
SESSION_COOKIE_SECURE = False
CSRF_COOKIE_SECURE = False
X_FRAME_OPTIONS = 'DENY'

# Application definition

INSTALLED_APPS = [
    'suit',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'Avtoregion',
    'bootstrap3',
    'Avtoregion.templatetags.verbose_names',
    'braces',
    'debug_toolbar'
]

MIDDLEWARE = [
    'debug_toolbar.middleware.DebugToolbarMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'Avtoregion.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')]
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'Avtoregion.template_context_processors.settings_context_processor',

            ],
        },
    },
]


WSGI_APPLICATION = 'Avtoregion.wsgi.application'

# Database
# https://docs.djangoproject.com/en/1.11/ref/settings/#databases

DATABASES = {
    'default': env.db(),
    'OPTIONS': {
        'init_command': 'SET sql_mode=STRICT_TRANS_TABLES'
    },
}

# Password validation
# https://docs.djangoproject.com/en/1.11/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]
LOGIN_URL = '/login/'
LOGIN_REDIRECT_URL = '/Race'

# Internationalization
# https://docs.djangoproject.com/en/1.11/topics/i18n/

LANGUAGE_CODE = 'ru-RU'

TIME_ZONE = 'Asia/Yekaterinburg'

USE_I18N = True

USE_L10N = True

USE_TZ = True


def md5sum(filename):
    md5 = hashlib.md5()
    with open(filename, 'rb') as f:
        for chunk in iter(lambda: f.read(128*md5.block_size), b''):
            md5.update(chunk)
    return md5.hexdigest()

STATIC_URL = '/static/'
MEDIA_URL = '/media/'
STATIC_ROOT = os.path.join(BASE_DIR, 'Avtoregion', 'static')
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
try:
    JS_FILE_MAIN = os.path.join(os.path.join(STATIC_ROOT, 'js'), 'main.js')
    JS_MAIN = md5sum(JS_FILE_MAIN)
    JS_FILE_BOOTSTRAP = os.path.join(os.path.join(STATIC_ROOT, 'js'), 'bootstraptable-config.js')
    JS_BOOTSTRAP = md5sum(JS_FILE_BOOTSTRAP)
    JS_FILE_CHOSEN = os.path.join(os.path.join(STATIC_ROOT, 'js'), 'chosen-config.js')
    JS_CHOSEN = md5sum(JS_FILE_CHOSEN)
    JS_FILE_DATERANGE = os.path.join(os.path.join(STATIC_ROOT, 'js'), 'datarange-config.js')
    JS_DATERANGE = md5sum(JS_FILE_DATERANGE)
    JS_FILE_MODAL = os.path.join(os.path.join(STATIC_ROOT, 'js'), 'modal-config.js')
    JS_MODAL = md5sum(JS_FILE_MODAL)
except:
    JS_MAIN = ""
    JS_BOOTSTRAP = ""
    JS_DATERANGE = ""
    JS_MODAL = ""
    JS_CHOSEN = ""
